### ISSUE TITLE
Pause time between texts increments on every loop

### ISSUE THREAD

**Issue by Valkween** [tameemsafi/typewriterjs#26] opened 2018-11-25 14:45 UTC
Tested using Chrome v70.0.3538.102 (64 bits) and Microsoft Edge v42.17134.1.0

Hi!
Testing the plugin today i discovered what it seems to be a bug. On every cycle the pause time between texts increments like 500ms more...

**Comment by CoderSquirrel** [comment] 2018-11-27 19:20
I'm facing the same issue, even i looked for the code and nothign seems to change

**Comment by tameemsafi** [comment] 2018-11-27 21:32
@CoderSquirrel I will check it now, so the problem is that the pause time between writing each characters keeps increasing? Is there a maximum it reaches?

At the moment the time between each character is random, so there is a variation, but it should not be increasing infinitely.

**Comment by CoderSquirrel** [comment] 2018-11-28 18:30
hi @tameemsafi  i notice that the diference starts to became visible after, 3rd, 4th cyrcle.

I used the custom `delay` but it seems to became strange on mobiles

the site i'm current using is www.jmjsistemas.com.br/new the 1st screen has it

**Comment by tameemsafi** [comment] 2018-12-02 21:53
@CoderSquirrel I think issue should now be fixed in latest version (2.5.1).

**Closed by tameemsafi** 2018-12-02 21:53 UTC
