### ISSUE TITLE
Cannot use strong characters within 1 string.

### ISSUE THREAD

**Issue by rolfoldenkotte** [tameemsafi/typewriterjs#21] opened 2018-10-16 09:06 UTC
Hello people from typewriterjs, I'm working on a project in which I have a string like: "<strong>Hello?! Hello! Can you hear me?</strong> If you can read this message, please hit next in the lower right to let me know if I am not just talking to myself!"

The message will stop typing after the strong lines are done. If i put strong lines like in the middle it will just stop working at all. Do you have a solution for this?

**Comment by tameemsafi** [comment] 2018-11-20 22:33
@rolfoldenkotte Could you try it with `v2.5.0` and let me know if the issue is still there?

**Comment by tameemsafi** [comment] 2019-06-16 10:07
I think it is working fine so will close this issue.

Example: https://jsfiddle.net/n2vj50s9/

**Closed by tameemsafi** 2019-06-16 10:07 UTC
